Implement basic blocks & threaded code
VasiliyMatr/sim2023 pull request #20
Opened 2023-12-03 22:34 UTC by VasiliyMatr

* Move status codes to common module
* Add routines for load & store ops
* Add bb module
* Add integration tests for simulator module
* Implement threaded code
* A few other fixes

2023-12-05 15:42 UTC, TheRedHotHabanero requested changes

2023-12-05 15:42 UTC, TheRedHotHabanero commented on bb/include/sim/bb.hpp
> +        SIM_ASSERT(0);
This line is unreachable

2023-12-05 15:42 UTC, TheRedHotHabanero commented on bb/include/sim/bb.hpp
> +        for (size_t i = 0; i < MAX_SIZE - 1; ++i) {
Is it correct? It will iterate [0...14]

2023-12-05 15:42 UTC, TheRedHotHabanero commented on csr/src/csr.cpp
> +#include "sim/csr/value.gen.hpp"
Common style for headers?

2023-12-05 15:42 UTC, TheRedHotHabanero commented on instr/CMakeLists.txt
> -set(RISCV_YAML ${CMAKE_CURRENT_SOURCE_DIR}/risc-v.yaml)
Why did you delete this line?

2023-12-05 15:42 UTC, TheRedHotHabanero commented on memory/include/sim/memory/mmu64.hpp
> +#include "sim/common.hpp"
Common style for headers?

2023-12-05 15:42 UTC, TheRedHotHabanero commented on sim_app/src/sim_app.cpp
> +#include "sim/common.hpp"
Common include style

2023-12-05 15:42 UTC, TheRedHotHabanero commented on simulator/include/sim/simulator.hpp
> +#include "sim/instr/instr_id.gen.hpp"
Style

2023-12-05 15:42 UTC, TheRedHotHabanero commented on simulator/tests/src/test_simulator.cpp
> +#include "sim/common.hpp"
Style

2023-12-05 17:40 UTC, VasiliyMatr commented on bb/include/sim/bb.hpp
> +        SIM_ASSERT(0);
And that's why I put assertion there

2023-12-05 17:46 UTC, VasiliyMatr commented on bb/include/sim/bb.hpp
> +        for (size_t i = 0; i < MAX_SIZE - 1; ++i) {
Yes, it is correct. Since there is status instruction insertion after the cycle. That instruction terminates bb

2023-12-05 17:48 UTC, VasiliyMatr commented on instr/CMakeLists.txt
> -set(RISCV_YAML ${CMAKE_CURRENT_SOURCE_DIR}/risc-v.yaml)
Since risc-v.yaml is moved to project root

2023-12-06 07:49 UTC, VasiliyMatr commented on csr/src/csr.cpp
> +#include "sim/csr/value.gen.hpp"
Fixed

2023-12-06 07:49 UTC, VasiliyMatr commented on memory/include/sim/memory/mmu64.hpp
> +#include "sim/common.hpp"
Fixed

2023-12-06 07:50 UTC, VasiliyMatr commented on sim_app/src/sim_app.cpp
> +#include "sim/common.hpp"
Fixed

2023-12-06 07:51 UTC, VasiliyMatr commented on simulator/include/sim/simulator.hpp
> +#include "sim/instr/instr_id.gen.hpp"
Fixed

2023-12-06 07:51 UTC, VasiliyMatr commented on simulator/tests/src/test_simulator.cpp
> +#include "sim/common.hpp"
Fixed

2023-12-06 08:05 UTC, TheRedHotHabanero approved these changes

2023-12-06 08:09 UTC, merged